src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface {

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Message", mappedBy="sender")
     */
    private $sentMsg;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Message", mappedBy="receiver")
     */
    private $receivedMsg;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $recovery;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Group", mappedBy="owner", orphanRemoval=true)
     */
    private $groups;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Friendship", mappedBy="sender", orphanRemoval=true)
     */
    private $friendships;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Friendship", mappedBy="receiver", orphanRemoval=true)
     */
    private $receivedFriendships;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Inbox", mappedBy="user", orphanRemoval=true)
     */
    private $inboxes;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $avatar;

    /**
     * User constructor.
     */
    public function __construct() {
        $this->sentMsg = new ArrayCollection();
        $this->receivedMsg = new ArrayCollection();
        $this->groups = new ArrayCollection();
        $this->inboxes = new ArrayCollection();
        $this->friendships = new ArrayCollection();
        $this->receivedFriendships = new ArrayCollection();
    }

    /**
     * Gets the ID of the User
     *
     * @return int|null
     */
    public function getId(): ?int {
        return $this->id;
    }

    /**
     * Returns the email address of the User
     *
     * @return string|null
     */
    public function getEmail(): ?string {
        return $this->email;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self {
        $this->roles = $roles;

        return $this;
    }

    /**
     * Gets the User's password
     *
     * @return string
     * @see UserInterface
     */
    public function getPassword(): string {
        return (string) $this->password;
    }

    /**
     * Updates the User's password
     *
     * @param string $password
     * @return $this
     */
    public function setPassword(string $password): self {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt() {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials() {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    /**
     * @return Collection|Group[]
     */
    public function getGroups(): Collection {
        return $this->groups;
    }

    /**
     * @return Collection|Inbox[]
     */
    public function getInboxes(): Collection {
        return $this->inboxes;
    }

    /**
     * @return Collection|Friendship[]
     */
    public function getFriendships(): Collection {
        return $this->friendships;
    }

    /**
     * @return Collection|Friendship[]
     */
    public function getReceivedFriendships(): Collection {
        return $this->receivedFriendships;
    }

    /**
     * Gets the name of the User
     *
     * @return string|null
     */
    public function getName(): ?string {
        return $this->name;
    }

    /**
     * Updates the name of the User
     *
     * @param string $name
     * @return $this
     */
    public function setName(string $name): self {
        $this->name = $name;

        return $this;
    }

    /**
     * Gets the User's friends
     *
     * @return ArrayCollection
     */
    public function getFriends() {
        $friends = new ArrayCollection();

         foreach ($this->getFriendships() as $friendship)
             if (!$friendship->isPending())
                $friends->add($friendship->getReceiver());

         foreach ($this->getReceivedFriendships() as $friendship)
             if (!$friendship->isPending())
                 $friends->add($friendship->getSender());

         return $friends;
    }

    /**
     * Gets the pending Friendship requests received by the User
     *
     * @return ArrayCollection
     */
    public function getFriendRequests() {
        $requests = new ArrayCollection();

        foreach ($this->getReceivedFriendships() as $friendship)
            if ($friendship->isPending())
                $requests->add($friendship);

        return $requests;
    }

    /**
     * Gets the User's avatar
     *
     * @return string|null
     */
    public function getAvatar(): ?string {
        return $this->avatar;
    }

    /**
     * Updates the User's avatar
     *
     * @param string|null $avatar
     * @return $this
     */
    public function setAvatar(?string $avatar): self {
        $this->avatar = $avatar;

        return $this;
    }
}

templates/_formModal.html.twig
<div class="modal fade" id="{{ formId }}">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h2 class="h5">{{ formTitle }}</h2>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                {{ form(form) }}
            </div>
        </div>
    </div>
</div>

templates/_header.html.twig
<header class="bg-white border-bottom shadow-sm h-25">
    <div class="container d-flex p-3 align-items-center">
        <a href="{{ path('home') }}" type="button" class="btn btn-light bg-transparent mr-md-auto border-0" id="home-button">
            <h5 class="my-0 font-weight-normal">Courier 2</h5>
        </a>
        <nav class="nav my-2 my-md-0 mr-md-3">
            {% if app.user %}
                {#<a href="{{ path('friends') }}" class="btn btn-link text-secondary" id="menu-friends">
                    Friends
                    {% if app.user.friendRequests.count != 0 %}
                        <span class="badge badge-info">{{ app.user.friendRequests.count }}</span>
                    {% endif %}
                </a>
                <a href="{{ path('groups') }}" class="btn btn-link text-secondary" id="menu-groups">Groups</a>
                <div class="dropdown">
                    <button class="btn btn-link text-secondary dropdown-toggle" id="menu-user" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ app.user.name }}</button>

                    <div class="dropdown-menu" aria-labelledby="menu-user">
                        <a href="{{ path('profile') }}" type="button" class="btn btn-link text-secondary dropdown-item" id="menu-profile">Profile</a>
                        <a href="{{ path('app_logout') }}" type="button" class="btn btn-link text-danger dropdown-item" id="menu-log-out">Log out</a>
                    </div>
                </div>#}

                <div class="media">
                    <div class="media-body d-inline-flex align-items-center">
                        <a href="{{ path('friends') }}" class="btn btn-link text-secondary" id="menu-friends">
                            Friends
                            {% if app.user.friendRequests.count != 0 %}
                                <span class="badge badge-info">{{ app.user.friendRequests.count }}</span>
                            {% endif %}
                        </a>
                        <a href="{{ path('groups') }}" class="btn btn-link text-secondary" id="menu-groups">Groups</a>
                        <div class="dropdown">
                            <button class="btn btn-link text-secondary dropdown-toggle" id="menu-user" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ app.user.name }}</button>

                            <div class="dropdown-menu" aria-labelledby="menu-user">
                                <a href="{{ path('profile') }}" type="button" class="btn btn-link text-secondary dropdown-item" id="menu-profile">Profile</a>
                                <a href="{{ path('app_logout') }}" type="button" class="btn btn-link text-danger dropdown-item" id="menu-log-out">Log out</a>
                            </div>
                        </div>
                    </div>
                    <img src="{{ asset('uploads/avatars/' ~ app.user.avatar) }}" alt="{{ app.user.name }}" class="rounded-circle" style="max-width:5vh!important;">
                </div>
            {% else %}
                <a href="{{ path('sign_in') }}" class="btn btn-link text-secondary" id="menu-sign-in">Sign in</a>
                <a href="{{ path('app_register') }}" type="button" class="btn btn-outline-secondary" id="menu-register">Register</a>
            {% endif %}
        </nav>
    </div>
</header>

templates/_userNameDisplay.html.twig
{% if app.user == user %}
    Me
{% elseif app.user.friends.contains(user) %}
    {{ user.name }} <span class="text-muted ml-1">({{ user.username }})</span>
{% else %}
    {{ user.username }}
{% endif %}

templates/base.html.twig
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}{% endblock %}Courier</title>

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

        <!-- Bootstrap JavaScript (jQuery & Popper.js) -->
        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous" defer></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous" defer></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous" defer></script>

        <!-- FontAwesome Kit -->
        <script src="https://kit.fontawesome.com/12f3abc7c3.js" crossorigin="anonymous" defer></script>
    </head>
    <body>
        {{ include('_header.html.twig') }}

        <section class="container pt-3 position-relative overflow-auto" id="main-container">
            <div class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center">
                <div id="alert-container">
                    {% if app.request.hasPreviousSession %}
                        {% for label, messages in app.flashes %}
                            {% for message in messages %}
                                <div class="alert alert-{{ label }} alert-dismissible fade show" role="alert">
                                    {{ message }}
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                            {% endfor %}
                        {% endfor %}
                    {% endif %}
                </div>
                {% block body %}{% endblock %}
            </div>
        </section>
    </body>
</html>

templates/home.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h1>Courier 2</h1>
    <a href="{{ path('sign_in') }}" class="btn btn-secondary" id="home-sign-in">Sign in</a>
    <a href="{{ path('app_register') }}" class="btn btn-secondary" id="home-register">Register</a>
{% endblock %}

templates/profile.html.twig
{% extends 'base.html.twig' %}

{% block title %}User profile - {% endblock %}

{% block body %}
    <h1 class="h3 my-3">{{ app.user.name }}</h1>

    <div class="w-75 m-auto">
        {{ form_start(profileForm) }}
            {{ form_widget(profileForm.name) }}
            {{ form_widget(profileForm.email) }}
            {{ form_widget(profileForm.newPassword) }}
            {{ form_widget(profileForm.avatar) }}
            <hr>
            {{ form_widget(profileForm.password) }}
        {{ form_end(profileForm) }}
    </div>
{% endblock %}